#!/usr/bin/env bash
find * -type f -name *.bz2 -delete
find * -type f -name *.deb -delete
find * -type f -name *.pkg.tar.xz -delete
find * -type f -name *.rpm -delete
find * -type f -name .AURINFO -delete
find * -type f -name .BUILDINFO -delete
find * -type f -name .INSTALL -delete
find * -type f -name .MTREE -delete
find * -type f -name .PKGINFO -delete
find * -type f -name .SRCINFO -delete
# find * -type f -name .directory -delete
find * -type f -name .gitignore -delete
find * -type d -name pkg -exec rm -rf {} +
find * -type d -name src -exec rm -rf {} +
find * -type f -exec chmod 644 {} +
find * -type d -exec chmod 755 {} +
if [ -f TREE ] ; then rm TREE && tree > TREE ; fi
